name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      bun-version: ${{ steps.get-bun.outputs.bun-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install native build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 g++ make

      - name: Setup Bun
        id: get-bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
